module.exports = {
    port: 5000,
    db_url:'mongodb+srv://admin:admin@cluster0.lzkrj.mongodb.net/myFirstDatabase?retryWrites=true&w=majority',
    ourUrl: 'http://localhost:5000',
    secret:'https://jwt.io/#debugger-io?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ',
    favIco: './PaginaPrincipala//favicon.ico',
    logoIndex: './PaginaPrincipala/logoRecipeCentralNormal-01.png',
    backgroundIndex: './PaginaPrincipala/Front_Page_background-01.png',
    userIndex1: './PaginaPrincipala/USER2-01.png',
    userIndex2: './PaginaPrincipala/USER1-01.png',
    userIndex3: './PaginaPrincipala/USER3-01.png',
    endBackgroundIndex: './PaginaPrincipala/end_background-01.png',
    descriptionImgIndex: './PaginaPrincipala/Description_div_image-01.png',
    logoForLabelIndex1: './PaginaPrincipala/logo1-01.png',
    logoForLabelIndex2: './PaginaPrincipala/logo2-01.png',
    logoForLabelIndex3: './PaginaPrincipala/logo3-01.png',
    twitterIcon: './Contact/twitter-icon-01.png',
    contactBk: './Contact/contactus-backgrounf-01.png',
    contactLogo: './Contact/logoRecipeCentralNormal-01.png',
    instagramIcon: './Contact/instagram-icon-01.png',
    phoneIcon: './Contact/phone-icon-01.png'
}